:PROPERTIES:
- org-mode configuration
#+TITLE: ASA SM1ST method comparison and RRF adjustment
#+AUTHOR:    Emiliy Desmoreaux, Brittany Wong, Nate McIntosh, Matthew Henderson
#+DATE:      \today
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:t toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:t ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:
#+LINK_HOME:
#+XSLT:
#+DRAWERS: LOGBOOK CLOCK HIDDEN PROPERTIES
#+STARTUP: overview
#+Latex_class: koma-article
#+LaTeX_header: \usepackage{textpos}
#+LaTeX_HEADER: \usepackage{amsmath}
#+LaTeX_HEADER: \usepackage{longtable}
#+LaTeX_HEADER: \usepackage[automark, autooneside=false, headsepline]{scrlayer-scrpage}
#+LaTeX_HEADER: \clearpairofpagestyles
#+LaTeX_HEADER: \ihead{\leftmark}% section on the inner (oneside: right) side
#+LaTeX_HEADER: \ohead{\rightmark}% subsection on the outer (oneside: left) side
#+LaTeX_HEADER: \ofoot*{\pagemark}% the pagenumber on the outer side of the foot, also on plain pages
#+LaTeX_HEADER: \pagestyle{scrheadings}
:END:



* Summary 

- SUAC concentrations are at the low end of the analytical range in the newborn population
  - Results from the SM1ST method are slightly higher in the population
    due to background signal (Figure [[fig:popdens]] and Table
    \ref{tab:summary})
- The low concentration population data can not be used to access the SM1ST and AAAAC comparison 
- The reported CDC mean values were selected as the source of truth
  for this method and results were aligned with the CDC mean values
  (Figure [[fig:suac_cdc]])
- Linearity materials, calibrators,EQA material and one elevated
  patient sample were used to assess comparability to the AAAC method
  after adjustment to align with CDC means (Figure [[fig:comp]])
- This linear regression model was used to transfer the current SUAC
  screening threshold to SM1ST assay
- A Monte Carlo simulation was used to estimate the number initial
  screen positive result per week for a set of potential screening
  cut-offs (Table \ref{tab:sim})
  - An initial screening cut-off of 3.0 uM would result in approximately
    one initial positive result per week with a maximum of 5.
  - This is equivalent to a value of 6.2 uM  on the AAAC assay.
- Short term follow-up data shows that all true positive tyrosinemia
  type 1 cases had a SUAC \gt 20 uM this would be equivalent to a
  result \gt 8.6 uM on the SM1ST assay
  - Based on this evidence we will use an alert threshold of 7 umol/L

- Based on the method comparison data, simulation of initial positive
  rate and review of screen positive cases we will use the following
  first tier screening cut-offs:

  - Initial positive :: 3 umol/L
  - Alert positive :: 7 umol/L
  

#+begin_src R :session *R* :results output :exports results :tangle yes
  library("tidyverse")
  library("readxl")
  library("mcr")
  library("stargazer")
  source("./functions.r")
  source("./queries.r")
  options(warn=-1) # 0 to turn on again
  options(dplyr.summarise.inform = FALSE)
  ## CDC adjustment
  ## ASA
  bill_asapop <- get_data("ASA", 20, query_population)
  bill_asalin <- get_data("ASA", 20, query_linearity)
  bill_asalin_distinct <- bill_asalin %>%
      distinct(date, sample, sm1st, .keep_all = TRUE) 

  bill_asaqc <- get_viewdata("ASA", query_qc)
  bill_asamoi <- get_viewdata("ASA", query_moi)

  larry_asapop <- get_csv_data("ASA", 20, "Larry", pop_csv_query)
  larry_asalin <- get_csv_data("ASA", 20, "Larry", linearity_csv_query)
  larry_asalin_distinct <- larry_asalin %>%
      distinct(date, sample, sm1st, .keep_all = TRUE) 
  larry_asaqc <- get_csv_viewdata("ASA", "Larry", qc_csv_query)
  larry_asamoi <- get_csv_viewdata("ASA", "Larry", moi_csv_query)

  joe_asapop <- get_csv_data("ASA", 20, "Joe", pop_csv_query)
  joe_asalin <- get_csv_data("ASA", 20, "Joe", linearity_csv_query)
  joe_asalin_distinct <- joe_asalin %>%
      distinct(date, sample, sm1st, .keep_all = TRUE) 
  joe_asaqc <- get_csv_viewdata("ASA", "Joe", qc_csv_query)
  joe_asamoi <- get_csv_viewdata("ASA", "Joe", moi_csv_query)

  ## cdc_data <- read.csv(file = "../data/ASA_CDClin.csv")

  ## asacomp <- read_xlsx(path = "../data/ASA_SM1ST vs AAAC and LCMS-ASA methods_AUG2025.xlsx", sheet = 5)
  volume <- read_xlsx(path = "../data/DashSnap_202207121456.xlsx", sheet = 1)

#+end_src

#+RESULTS:
#+begin_example
── [1mAttaching core tidyverse packages[22m ────────────────────────────────────────────────────────────────────────────────── tidyverse 2.0.0 ──
[32m✔[39m [34mdplyr    [39m 1.1.0     [32m✔[39m [34mreadr    [39m 2.1.4
[32m✔[39m [34mforcats  [39m 1.0.0     [32m✔[39m [34mstringr  [39m 1.5.0
[32m✔[39m [34mggplot2  [39m 3.4.1     [32m✔[39m [34mtibble   [39m 3.1.8
[32m✔[39m [34mlubridate[39m 1.9.2     [32m✔[39m [34mtidyr    [39m 1.3.0
[32m✔[39m [34mpurrr    [39m 1.0.1     
── [1mConflicts[22m ──────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
[31m✖[39m [34mdplyr[39m::[32mfilter()[39m masks [34mstats[39m::filter()
[31m✖[39m [34mdplyr[39m::[32mlag()[39m    masks [34mstats[39m::lag()
[36mℹ[39m Use the conflicted package ([3m[34m<http://conflicted.r-lib.org/>[39m[23m) to force all conflicts to become errors

Please cite as: 

 Hlavac, Marek (2022). stargazer: Well-Formatted Regression and Summary Statistics Tables.
 R package version 5.2.3. https://CRAN.R-project.org/package=stargazer
Error: Unknown column 'csvqc.ASA' in 'field list' [1054]
Error: Unknown column 'csvmoi.ASA' in 'field list' [1054]
Error: Unknown column 'csvqc.ASA' in 'field list' [1054]
Error: Unknown column 'csvmoi.ASA' in 'field list' [1054]
Error in file(file, "rt") : cannot open the connection
Error: `path` does not exist: ‘../data/ASA_SM1ST vs AAAC and LCMS-ASA methods_AUG2025.xlsx’
#+end_example



#+begin_src R :session *R* :results output graphics file :file ../figures/Bill/asa_dens.pdf :exports results :tangle yes
  ggplot(bill_asapop) +
    geom_density(aes(x = aaac, colour = aaac_instrument)) +
    geom_density(aes(x = sm1st)) +
    coord_cartesian(xlim = c(0,20))
#+end_src

#+CAPTION[]: Bill ASA distribution in population by assay and instrument 
#+NAME: fig:popdens
#+ATTR_LaTeX: :width 0.9\textwidth
#+RESULTS:
[[file:../figures/Bill/asa_dens.pdf]]


#+begin_src R :session *R* :results output graphics file :file ../figures/Larry/asa_dens.pdf :exports results :tangle yes
  ggplot(larry_asapop) +
    geom_density(aes(x = aaac, colour = aaac_instrument)) +
    geom_density(aes(x = sm1st)) +
    coord_cartesian(xlim = c(0,20))
#+end_src

#+CAPTION[]: Larry ASA distribution in population by assay and instrument 
#+NAME: fig:popdens
#+ATTR_LaTeX: :width 0.9\textwidth
#+RESULTS:
[[file:../figures/Larry/asa_dens.pdf]]


#+begin_src R :session *R* :results output graphics file :file ../figures/Joe/asa_dens.pdf :exports results :tangle yes
  ggplot(joe_asapop) +
    geom_density(aes(x = aaac, colour = aaac_instrument)) +
    geom_density(aes(x = sm1st)) +
    coord_cartesian(xlim = c(0,20))
#+end_src

#+CAPTION[]: Joe ASA distribution in population by assay and instrument 
#+NAME: fig:popdens
#+ATTR_LaTeX: :width 0.9\textwidth
#+RESULTS:
[[file:../figures/Joe/asa_dens.pdf]]


* CDC alignment RRF

#+begin_src R :session *R* :results output :exports results :tangle yes
  ### CDC mean value
  larry_rrf <- 1 #make_cdc(larry_asalin_distinct, cdc_data, "Larry", "ASA")
  bill_rrf <- 1 #make_cdc(bill_asalin_distinct, cdc_data, "Bill", "ASA")
  joe_rrf <- 1 #make_cdc(joe_asalin_distinct, cdc_data, "Joe", "ASA")

  make_plots("ASA_CDC", bill_asapop, bill_asalin, bill_rrf, 4, 10 , "Bill")
  make_ts("ASA_CDC", bill_asaqc, bill_asamoi, bill_rrf, "Bill")
  make_mcr("ASA", bill_asapop, bill_asalin, bill_asaqc, c("ASA" = bill_rrf), "Bill")

  make_plots("ASA_CDC", joe_asapop, joe_asalin, joe_rrf, 4, 10, "Joe")
  make_ts("ASA_CDC", joe_asaqc, joe_asamoi, joe_rrf, "Joe")
  make_mcr("ASA", joe_asapop, joe_asalin, joe_asaqc, c("ASA" = joe_rrf), "Joe")

  make_plots("ASA_CDC", larry_asapop, larry_asalin, larry_rrf, 4, 10, "Larry")
  make_ts("ASA_CDC", larry_asaqc, larry_asamoi, larry_rrf, "Larry")
  make_mcr("ASA", larry_asapop, larry_asalin, larry_asaqc, c("ASA" = larry_rrf), "Larry")

#+end_src

#+RESULTS:
#+begin_example
[1m[22mSaving 7 x 7 in image
[1m[22m`geom_smooth()` using formula = 'y ~ x'
[1m[22m`geom_smooth()` using formula = 'y ~ x'
[1m[22m`geom_smooth()` using formula = 'y ~ x'
[1m[22mSaving 7 x 7 in image
pdf 
  2
[1m[22mSaving 7 x 7 in image
[1m[22m`geom_smooth()` using formula = 'y ~ x'
[1m[22m`geom_smooth()` using formula = 'y ~ x'
[1m[22m`geom_smooth()` using formula = 'y ~ x'
[1m[22mSaving 7 x 7 in image
pdf 
  2
[1m[22mSaving 7 x 7 in image
[1m[22m`geom_smooth()` using formula = 'y ~ x'
[1m[22m`geom_smooth()` using formula = 'y ~ x'
[1m[22m`geom_smooth()` using formula = 'y ~ x'
[1m[22mSaving 7 x 7 in image
pdf 
  2
#+end_example

** Bill

#+CAPTION[]:Bill ASA CDC linearity comparison 
#+NAME: fig:asa_cdc
#+ATTR_LaTeX: :width 1\textwidth
[[file:../figures/Bill/ASA_CDC_regression.pdf]]

\clearpage

#+CAPTION[]:Bill ASA CDC and linearity based RRF adjustment
#+NAME: fig:ASA_CDC_pop
#+ATTR_LaTeX: :width 1\textwidth
[[file:../figures/Bill/ASA_CDC.pdf]]

\clearpage

#+CAPTION[]:Bill ASA QC and MOI comparison with CDC based RRF adjustment
#+NAME: fig:ASA_CDC_qc
#+ATTR_LaTeX: :width 1\textwidth
[[file:../figures/Bill/ASA_CDC_ts.pdf]]


#+CAPTION[]:Bill ASA SM1ST and AAAC regression after RRF adjustment
#+NAME: fig:ASA_reg
#+ATTR_LaTeX: :width 1\textwidth
[[file:../figures/Bill/ASA_regression.pdf]]

\clearpage


#+begin_src R :session *R* :results output latex :exports results :tangle yes
  bill_asapop$sm1st_rrf <- bill_asapop$sm1st * bill_rrf
  stargazer(bill_asapop, title = "Bill Summary statistics", label = "tab:bill_summary")
#+end_src

#+RESULTS:
#+begin_export latex

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Tue, Sep 16, 2025 - 04:57:43 PM
\begin{table}[!htbp] \centering 
  \caption{Bill Summary statistics} 
  \label{tab:bill_summary} 
\begin{tabular}{@{\extracolsep{5pt}}lccccc} 
\\[-1.8ex]\hline 
\hline \\[-1.8ex] 
Statistic & \multicolumn{1}{c}{N} & \multicolumn{1}{c}{Mean} & \multicolumn{1}{c}{St. Dev.} & \multicolumn{1}{c}{Min} & \multicolumn{1}{c}{Max} \\ 
\hline \\[-1.8ex] 
sm1st & 10,168 & 8.120 & 3.727 & 0.400 & 20.000 \\ 
aaac & 10,168 & 0.566 & 0.296 & 0.000 & 6.900 \\ 
sm1st\_rrf & 10,168 & 8.120 & 3.727 & 0.400 & 20.000 \\ 
\hline \\[-1.8ex] 
\end{tabular} 
\end{table}
#+end_export


** Larry  
#+CAPTION[]:Larry ASA CDC linearity comparison 
#+NAME: fig:asa_cdc
#+ATTR_LaTeX: :width 1\textwidth
[[file:../figures/Larry/ASA_CDC_regression.pdf]]

\clearpage

#+CAPTION[]:Larry ASA CDC and linearity based RRF adjustment
#+NAME: fig:ASA_CDC_pop
#+ATTR_LaTeX: :width 1\textwidth
[[file:../figures/Larry/ASA_CDC.pdf]]

\clearpage

#+CAPTION[]:Larry ASA QC and MOI comparison with CDC based RRF adjustment
#+NAME: fig:ASA_CDC_qc
#+ATTR_LaTeX: :width 1\textwidth
[[file:../figures/Larry/ASA_CDC_ts.pdf]]


#+CAPTION[]:Larry ASA SM1ST and AAAC regression after RRF adjustment
#+NAME: fig:ASA_reg
#+ATTR_LaTeX: :width 1\textwidth
[[file:../figures/Larry/ASA_regression.pdf]]


\clearpage


#+begin_src R :session *R* :results output latex :exports results :tangle yes
  larry_asapop$sm1st_rrf <- larry_asapop$sm1st * larry_rrf
  stargazer(larry_asapop, title = "Larry Summary statistics", label = "tab:larry_summary")
#+end_src

#+RESULTS:
#+begin_export latex

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Tue, Sep 16, 2025 - 04:57:54 PM
\begin{table}[!htbp] \centering 
  \caption{Larry Summary statistics} 
  \label{tab:larry_summary} 
\begin{tabular}{@{\extracolsep{5pt}}lccccc} 
\\[-1.8ex]\hline 
\hline \\[-1.8ex] 
Statistic & \multicolumn{1}{c}{N} & \multicolumn{1}{c}{Mean} & \multicolumn{1}{c}{St. Dev.} & \multicolumn{1}{c}{Min} & \multicolumn{1}{c}{Max} \\ 
\hline \\[-1.8ex] 
sm1st & 1,707 & 9.689 & 3.518 & 0.157 & 20.000 \\ 
aaac & 1,707 & 0.552 & 0.173 & 0.100 & 1.700 \\ 
sm1st\_rrf & 1,707 & 9.689 & 3.518 & 0.157 & 20.000 \\ 
\hline \\[-1.8ex] 
\end{tabular} 
\end{table}
#+end_export

** Joe
#+CAPTION[]:Joe ASA CDC linearity comparison 
#+NAME: fig:asa_cdc
#+ATTR_LaTeX: :width 1\textwidth
[[file:../figures/Joe/ASA_CDC_regression.pdf]]

\clearpage

#+CAPTION[]:Joe ASA CDC and linearity based RRF adjustment
#+NAME: fig:ASA_CDC_pop
#+ATTR_LaTeX: :width 1\textwidth
[[file:../figures/Joe/ASA_CDC.pdf]]

\clearpage

#+CAPTION[]:Joe ASA QC and MOI comparison with CDC based RRF adjustment
#+NAME: fig:ASA_CDC_qc
#+ATTR_LaTeX: :width 1\textwidth
[[file:../figures/Joe/ASA_CDC_ts.pdf]]

#+CAPTION[]:Joe ASA SM1ST and AAAC regression after RRF adjustment
#+NAME: fig:ASA_reg
#+ATTR_LaTeX: :width 1\textwidth
[[file:../figures/Joe/ASA_regression.pdf]]

\clearpage


#+begin_src R :session *R* :results output latex :exports results :tangle yes
  joe_asapop$sm1st_rrf <- joe_asapop$sm1st * joe_rrf
  stargazer(joe_asapop, title = "Joe Summary statistics", label = "tab:joe_summary")
#+end_src

#+RESULTS:
#+begin_export latex

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Tue, Sep 16, 2025 - 04:57:59 PM
\begin{table}[!htbp] \centering 
  \caption{Joe Summary statistics} 
  \label{tab:joe_summary} 
\begin{tabular}{@{\extracolsep{5pt}}lccccc} 
\\[-1.8ex]\hline 
\hline \\[-1.8ex] 
Statistic & \multicolumn{1}{c}{N} & \multicolumn{1}{c}{Mean} & \multicolumn{1}{c}{St. Dev.} & \multicolumn{1}{c}{Min} & \multicolumn{1}{c}{Max} \\ 
\hline \\[-1.8ex] 
sm1st & 1,245 & 7.761 & 2.469 & 0.321 & 19.990 \\ 
aaac & 1,245 & 0.642 & 0.240 & 0.000 & 2.000 \\ 
sm1st\_rrf & 1,245 & 7.761 & 2.469 & 0.321 & 19.990 \\ 
\hline \\[-1.8ex] 
\end{tabular} 
\end{table}
#+end_export



* COMMENT Comparison

** Bill
- What is the equivalent of AAAC 5 uM with SM1ST after CDC adjustment?
- Linearity materials, calibrators,EQA material and one elevated patient sample were used to assess comparability.

#+begin_src R :session *R* :results output graphics file :file ../figures/Bill/ASA_mcr_linreg.pdf :exports results :tangle yes
  asacomp$Billcdc <- asacomp$Bill * bill_rrf

  asatrim <- asacomp %>%
      filter(AAAC <= 20)

  asa_comp.linreg <- mcreg(x = asatrim$AAAC, y =asatrim$Billcdc, error.ratio = 1, alpha = 0.05,
			    mref.name = "AAAC", mtest.name = "SM1ST CDC adj", sample.names = NULL,
			    method.reg = "LinReg", method.ci = "bootstrap",
			    method.bootstrap.ci = "BCa",
			    nsamples = 999, rng.seed = NULL, rng.kind = "Mersenne-Twister", iter.max = 30,
			    threshold = 1e-06, na.rm = TRUE, NBins = 1e+06)

  plot(asa_comp.linreg, x.lab = "AAAC", y.lab = "SM1ST CDC adj", main="Bill ASA comparison")

#+end_src


#+CAPTION[]: Comparison between SM1ST and AAAC 
#+NAME: fig:comp 
#+ATTR_LaTeX: :width 0.9\textwidth
#+RESULTS:
[[file:../figures/Bill/ASA_mcr_linreg.pdf]]


#+begin_src R :session *R* :results output graphics file :file ../figures/Bill/ASA_diff.pdf :exports results :tangle yes
plotDifference(asa_comp.linreg, main= "Bill ASA comparison")
#+end_src

#+CAPTION[]: Difference plot for SM1ST and AAAC 
#+NAME: fig:diff 
#+ATTR_LaTeX: :width 0.9\textwidth
#+RESULTS:
[[file:../figures/Bill/ASA_diff.pdf]]


#+begin_src R :session *R* :results output latex :exports results :tangle yes
  intercept <- asa_comp.linreg@para[1,1] # intercept
  slope <-  asa_comp.linreg@para[2,1] # slope

  reg <- function(m,x,b){
	y <- m * x + b
	return(round(y, digits = 3))
  }
#+end_src

- A result of src_R[:session *R* :results output :exports results :tangle yes]{reg(slope, 5, intercept)} uM with the SM1ST assay is
  equivalent to a value at the screening threshold (5 uM) with the AAAC method.


\clearpage

** Larry
- What is the equivalent of AAAC 5 uM with SM1ST after CDC adjustment?
- Linearity materials, calibrators,EQA material and one elevated patient sample were used to assess comparability.

#+begin_src R :session *R* :results output graphics file :file ../figures/Larry/ASA_mcr_linreg.pdf :exports results :tangle yes
 asacomp$Larrycdc <- asacomp$Larry * larry_rrf

 asatrim <- asacomp %>%
     filter(AAAC <= 20)

  asa_comp.linreg <- mcreg(x = asatrim$AAAC, y =asatrim$Larrycdc, error.ratio = 1, alpha = 0.05,
			    mref.name = "AAAC", mtest.name = "SM1ST CDC adj", sample.names = NULL,
			    method.reg = "LinReg", method.ci = "bootstrap",
			    method.bootstrap.ci = "BCa",
			    nsamples = 999, rng.seed = NULL, rng.kind = "Mersenne-Twister", iter.max = 30,
			    threshold = 1e-06, na.rm = TRUE, NBins = 1e+06)

  plot(asa_comp.linreg, x.lab = "AAAC", y.lab = "SM1ST CDC adj", main="Larry ASA comparison")

#+end_src


#+CAPTION[]: Comparison between SM1ST and AAAC 
#+NAME: fig:comp 
#+ATTR_LaTeX: :width 0.9\textwidth
#+RESULTS:
[[file:../figures/Larry/ASA_mcr_linreg.pdf]]


#+begin_src R :session *R* :results output graphics file :file ../figures/Larry/ASA_diff.pdf :exports results :tangle yes
plotDifference( asa_comp.linreg, main= "Larry ASA comparison")
#+end_src

#+CAPTION[]: Difference plot for SM1ST and AAAC 
#+NAME: fig:diff 
#+ATTR_LaTeX: :width 0.9\textwidth
#+RESULTS:
[[file:../figures/Larry/ASA_diff.pdf]]


#+begin_src R :session *R* :results output latex :exports results :tangle yes
  intercept <- asa_comp.linreg@para[1,1] # intercept
  slope <-  asa_comp.linreg@para[2,1] # slope

  reg <- function(m,x,b){
	y <- m * x + b
	return(round(y, digits = 3))
  }
#+end_src

- A result of src_R[:session *R* :results output :exports results :tangle yes]{reg(slope, 5, intercept)} uM with the SM1ST assay is
  equivalent to a value at the screening threshold (5 uM) with the AAAC method.


\clearpage

** Joe
- What is the equivalent of AAAC 5 uM with SM1ST after CDC adjustment?
- Linearity materials, calibrators,EQA material and one elevated patient sample were used to assess comparability.

#+begin_src R :session *R* :results output graphics file :file ../figures/Joe/ASA_mcr_linreg.pdf :exports results :tangle yes
  asacomp$Joecdc <- asacomp$Joe * joe_rrf

  asatrim <- asacomp %>%
      filter(AAAC <= 20)

  asa_comp.linreg <- mcreg(x = asatrim$AAAC, y =asatrim$Joecdc, error.ratio = 1, alpha = 0.05,
			    mref.name = "AAAC", mtest.name = "SM1ST CDC adj", sample.names = NULL,
			    method.reg = "LinReg", method.ci = "bootstrap",
			    method.bootstrap.ci = "BCa",
			    nsamples = 999, rng.seed = NULL, rng.kind = "Mersenne-Twister", iter.max = 30,
			    threshold = 1e-06, na.rm = TRUE, NBins = 1e+06)

  plot(asa_comp.linreg, x.lab = "AAAC", y.lab = "SM1ST CDC adj", main="Joe ASA comparison")

#+end_src


#+CAPTION[]: Comparison between SM1ST and AAAC 
#+NAME: fig:comp 
#+ATTR_LaTeX: :width 0.9\textwidth
#+RESULTS:
[[file:../figures/Joe/ASA_mcr_linreg.pdf]]


#+begin_src R :session *R* :results output graphics file :file ../figures/Joe/ASA_diff.pdf :exports results :tangle yes
plotDifference( asa_comp.linreg, main= "Joe ASA comparison")
#+end_src

#+CAPTION[]: Difference plot for SM1ST and AAAC 
#+NAME: fig:diff 
#+ATTR_LaTeX: :width 0.9\textwidth
#+RESULTS:
[[file:../figures/Joe/ASA_diff.pdf]]


#+begin_src R :session *R* :results output latex :exports results :tangle yes
  intercept <- asa_comp.linreg@para[1,1] # intercept
  slope <-  asa_comp.linreg@para[2,1] # slope

  reg <- function(m,x,b){
	y <- m * x + b
	return(round(y, digits = 3))
  }
#+end_src

- A result of src_R[:session *R* :results output :exports results :tangle yes]{reg(slope, 5, intercept)} uM with the SM1ST assay is
  equivalent to a value at the screening threshold (5 uM) with the AAAC method.


\clearpage

* COMMENT Simulation

- The intention of this simulation is to determine the impact of potential first tier ASA thresholds
- Inputs:
  - Weekly NBS sample volume: Sampled from a normal distribution with mean 2840
    and SD 297
    - Based on weekly volumes 2020-01-01 to 2021-12-31
  - ASA screening thresholds ranging from 2.5 (equivalent to 5 with AAAC) to 5 (equivalent to 10 with AAAC) 
- Method:
  - The ASA  population data (n ~ 12,000) was sampled 1000 times
    - The size of the weekly population sample was derived from a
      normal distribution with mean 2840 and SD 297
  - The ASA threshold applied was varied from 2.5 to 3.0 in increments
    of 0.1 for each population sample
    - The ASA logic using the current threshold was applied to each
      result in the population sample.
  - The number of results \ge the threshold for each data sample was recorded


#+begin_src R :session *R* :results output :exports results :tangle yes
    ###### weekly volumes
    ## volume$date_time  <- ymd_hms(volume$DateTime)
    ##   volume$nbs_entered_today<- as.numeric(volume$NBSEnteredToday)

    ##   volume_week <- volume %>%
    ## 	  group_by(week = date(floor_date(date_time, unit = "week"))) %>%
    ## 	  summarise(sum = sum(nbs_entered_today)) %>%
    ## 	  filter(week >= "2020-01-01" & week <= "2021-12-31") ## Two years

    ##   ggplot(volume_week) +
    ##     geom_histogram(aes(x=sum), binwidth = 100)

    start <- 2.5
    end <- 5
    mean_volume= 2840
    sd_volume= 297


  merge_asapop <- rbind(bill_asapop, larry_asapop, joe_asapop)
  
  asa_initial_logic <- function(data, threshold) {
					      #positives <- filter(data, GUAC >= threshold)
      positive <- length(data[data >= threshold])
      return(positive)
    }  
					    #  guac_initial_logic(nbs$GUAC, 2.7)
    citinitial <- data.frame(sample = double(), volume = double(), threshold= double(),
			    initial_positive = double(), stringsAsFactors = FALSE)
    c <- 0
    for (s in 1:1000) {
      v <- rnorm(n=1, mean = mean_volume, sd = sd_volume) ## sample volume$date
      data_sample <- sample(merge_asapop$sm1st_rrf, v, replace = FALSE)
      for (t in seq(from = start, to = end, by = 0.1)) {
	c <- c + 1
	p <- asa_initial_logic(data=data_sample, threshold=t)
	citinitial[c,] <- list(sample = s, volume=v, threshold = t, initial_positive =p)
      }
    }

#+end_src

#+RESULTS:


#+begin_src R :session *R* :results output latex :exports results :tangle yes
  citinitial %>%
    group_by(threshold) %>%
    summarise( min = min(initial_positive),
	      p025 = quantile(initial_positive,probs = c(0.025), type = 8, na.rm = TRUE),
	      median = median(initial_positive, na.rm = TRUE),
	      p975 = quantile(initial_positive,probs = c(0.975), type = 8, na.rm = TRUE),
	      max = max(initial_positive)) %>%
    as.data.frame() %>%
					# write.csv(,file = "../data/tyr1_simulation.csv") 
    stargazer(summary = FALSE, rownames = FALSE,
	      title="Output of Cit initial logic simulation for weekly volumes" ,
		label = "tab:sim")

#+end_src

#+RESULTS:
#+begin_export latex

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Fri, Sep 05, 2025 - 05:34:57 PM
\begin{table}[!htbp] \centering 
  \caption{Output of Tyr1 initial logic simulation for weekly volumes} 
  \label{tab:sim} 
\begin{tabular}{@{\extracolsep{5pt}} cccccc} 
\\[-1.8ex]\hline 
\hline \\[-1.8ex] 
threshold & min & p025 & median & p975 & max \\ 
\hline \\[-1.8ex] 
$2.500$ & $0$ & $2$ & $6$ & $11$ & $14$ \\ 
$2.600$ & $0$ & $0.342$ & $4$ & $7$ & $10$ \\ 
$2.700$ & $0$ & $0$ & $3$ & $6$ & $9$ \\ 
$2.800$ & $0$ & $0$ & $2$ & $5$ & $7$ \\ 
$2.900$ & $0$ & $0$ & $2$ & $4$ & $6$ \\ 
$3$ & $0$ & $0$ & $1$ & $4$ & $5$ \\ 
$3.100$ & $0$ & $0$ & $1$ & $3$ & $4$ \\ 
$3.200$ & $0$ & $0$ & $1$ & $3$ & $4$ \\ 
$3.300$ & $0$ & $0$ & $1$ & $2$ & $3$ \\ 
$3.400$ & $0$ & $0$ & $0$ & $2$ & $2$ \\ 
$3.500$ & $0$ & $0$ & $0$ & $1$ & $1$ \\ 
$3.600$ & $0$ & $0$ & $0$ & $1$ & $1$ \\ 
$3.700$ & $0$ & $0$ & $0$ & $1$ & $1$ \\ 
$3.800$ & $0$ & $0$ & $0$ & $1$ & $1$ \\ 
$3.900$ & $0$ & $0$ & $0$ & $1$ & $1$ \\ 
$4$ & $0$ & $0$ & $0$ & $1$ & $1$ \\ 
$4.100$ & $0$ & $0$ & $0$ & $1$ & $1$ \\ 
$4.200$ & $0$ & $0$ & $0$ & $1$ & $1$ \\ 
$4.300$ & $0$ & $0$ & $0$ & $1$ & $1$ \\ 
$4.400$ & $0$ & $0$ & $0$ & $1$ & $1$ \\ 
$4.500$ & $0$ & $0$ & $0$ & $1$ & $1$ \\ 
$4.600$ & $0$ & $0$ & $0$ & $1$ & $1$ \\ 
$4.700$ & $0$ & $0$ & $0$ & $1$ & $1$ \\ 
$4.800$ & $0$ & $0$ & $0$ & $1$ & $1$ \\ 
$4.900$ & $0$ & $0$ & $0$ & $1$ & $1$ \\ 
$5$ & $0$ & $0$ & $0$ & $1$ & $1$ \\ 
\hline \\[-1.8ex] 
\end{tabular} 
\end{table}
#+end_export
